<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>

    <!-- Packaging metadata -->
    <PackageId>Dhpke.Hpke.CSharp</PackageId>
    <Version>0.1.4</Version>
    <Authors>Kenji Otsuka</Authors>
    <!-- <Company>dhpke</Company> -->
    <Description>HPKE .NET facade (C#) over F# core implementation. Supports Base/PSK/Auth/AuthPSK modes with pluggable strategies.</Description>
    <PackageTags>hpke;cryptography;hpke-dotnet;hpke-csharp</PackageTags>
    <RepositoryUrl>https://github.com/KenjiOhtsuka/dhpke</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hpke\Hpke.fsproj" />
  </ItemGroup>

</Project>
