<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Packaging metadata for core F# library -->
    <PackageId>Dhpke.Hpke</PackageId>
    <Version>0.1.4</Version>
    <Authors>Kenji Otsuka</Authors>
    <!-- <Company>dhpke</Company> -->
    <Description>HPKE core primitives and mode implementations (F#). Do not reference this package directly from untrusted code.</Description>
    <PackageTags>hpke;cryptography;hpke-fsharp;hpke-core</PackageTags>
    <RepositoryUrl>https://github.com/KenjiOhtsuka/dhpke</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Core\Types.fs" />
    <Compile Include="Core\Crypto.fs" />
    <Compile Include="Core\Errors.fs" />
    <Compile Include="Core\Requests.fs" />
    <Compile Include="Core\Base.fs" />
    <Compile Include="Core\Psk.fs" />
    <Compile Include="Core\Auth.fs" />
    <Compile Include="Core\AuthPsk.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
